import os

RABBIT_ADDRESS = os.environ['RMQ_NET_ALIAS']

IN_QUEUE = 'in_queue'
OUT_QUEUE = os.environ['ML_GENERATION_QUEUE']

DB_FUNCTIONAL_SERVICE_EXCHANGE = os.environ['DB_FUNCTIONAL_SERVICE_EXCHANGE']
DB_FUNCTIONAL_SERVICE_QUEUE = os.environ['DB_FUNCTIONAL_SERVICE_QUEUE']
DB_FUNCTIONAL_SERVICE_ROUTING_KEY = os.environ['DB_FUNCTIONAL_SERVICE_ROUTING_KEY']

ML_GENERATION_EXCHANGE = os.environ['ML_GENERATION_EXCHANGE']
ML_GENERATION_QUEUE = os.environ['ML_GENERATION__QUEUE']
ML_GENERATION_ROUTING_KEY = os.environ['ML_GENERATION_ROUTING_KEY']

CONTAINS_QUERY_EXCHANGE = 'contains_query'
CONTAINS_QUERY_QUEUE = 'contains_queue'
CONTAINS_QUERY_ROUTING_KEY = 'contains_rk'

NEW_QUERIES_CSV_FOLDER = 'new_queries/'
NEW_QUERIES_PREFIX_FOR_SENDING = '../data_preprocessing/new_queries/'

INSERT_BEFORE_PREPROCESSING_QUERY_EXCHANGE = 'insert_before_preprocessing'
INSERT_BEFORE_PREPROCESSING_QUERY_QUEUE = 'insert_before_preprocessing_queue'
INSERT_BEFORE_PREPROCESSING_QUERY_ROUTING_KEY = 'insert_before_preprocessing_rk'

CUSTOMER_LISTS_QUERY_EXCHANGE = 'customer_lists'
CUSTOMER_LISTS_QUERY_QUEUE = 'customer_lists_queue'
CUSTOMER_LISTS_QUERY_ROUTING_KEY = 'customer_lists_rk'

INSERT_AFTER_PREPROCESSING_QUERY_EXCHANGE = 'insert_after_preprocessing'
INSERT_AFTER_PREPROCESSING_QUERY_QUEUE = 'insert_after_preprocessing_queue'
INSERT_AFTER_PREPROCESSING_QUERY_ROUTING_KEY = 'insert_after_preprocessing_rk'
