import util.parse_env as pe


################################################################################
# Global setup.

RMQ_NET_ALIAS = pe.get("RMQ_NET_ALIAS")

ML_GENERATION_EXCHANGE = pe.get("ML_GENERATION_EXCHANGE")
ML_GENERATION_QUEUE = pe.get("ML_GENERATION_QUEUE")
ML_GENERATION_ROUTING_KEY = pe.get("ML_GENERATION_ROUTING_KEY")

DB_FUNCTIONAL_SERVICE_EXCHANGE = pe.get("DB_FUNCTIONAL_SERVICE_EXCHANGE")
DB_FUNCTIONAL_SERVICE_QUEUE = pe.get("DB_FUNCTIONAL_SERVICE_QUEUE")
DB_FUNCTIONAL_SERVICE_ROUTING_KEY = pe.get(
    "DB_FUNCTIONAL_SERVICE_ROUTING_KEY"
)

PDF_GENERATION_EXCHANGE = pe.get("PDF_GENERATION_EXCHANGE")
PDF_GENERATION_QUEUE = pe.get("PDF_GENERATION_QUEUE")
PDF_GENERATION_ROUTING_KEY = pe.get("PDF_GENERATION_ROUTING_KEY")

################################################################################
# Local setup.

CO_GEN_EXCHANGE = ML_GENERATION_EXCHANGE
CO_GEN_QUEUE = f"{ML_GENERATION_QUEUE}_1"
CO_GEN_ROUTING_KEY = "ml_gen.gen"
